name: Tests

on: push

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.17" # This will match the latest 1.x version

      - name: Check out code
        uses: actions/checkout@v3

      - name: Get dependencies
        run: go mod download

      - name: Test
        run: go test -v ./...
